/** @type { import('@storybook/react-webpack5').StorybookConfig } */
const config = {
  //  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  stories: [
    "../src/stories/components/VgGraph/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgMapControl/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgTextEditor/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgButton/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgBadge/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgTextbox/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgTextarea/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgCheckbox/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgTooltip/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgBottomSheet/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgImageUploader/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgPopup/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgAiPopup/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgAvatar/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgPassiveNotification/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgToggle/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgLinkControl/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgDatePicker/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgTimePicker/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgSegments/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgPhoneControl/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgAddressControl/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgDropdown/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgDateRangePicker/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgColorPicker/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgTokens/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgSvg/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgMapControl/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgTables/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgReviewRating/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgStepper/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgCarousel/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgVideoPlayer/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgThreeDotMenu/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgSmileyInput/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgLoginInput/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgRadio/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgTab/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgCheckoutCustomerDropdown/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgNestedDropdown/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgImageDropdown/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgSlider/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgDragList/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgCustomerDropdown/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgAlert/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgInformationNote/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgForm/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgAccordion/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgProgressBar/*.stories.@(js|jsx|mjs|ts|tsx)",
    "../src/stories/components/VgSearchDropdown/*.stories.@(js|jsx|mjs|ts|tsx)",

  ],
  addons: [
    "@storybook/preset-create-react-app",
    "@storybook/addon-onboarding",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@chromatic-com/storybook",
    "@storybook/addon-interactions",
    "@storybook/addon-a11y",
  ],
  framework: {
    name: "@storybook/react-webpack5",
    options: {},
  },
  staticDirs: ["../public"],
};
export default config;
